version: "3.7"
services:
  ui:
    build: ./ui
    volumes:
      - ./ui/:/app
      - /app/node_modules
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    tty: true

  api:
    build: ./api
    volumes:
      - ./api/:/app
      - /app/deps
      - /app/_build

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - ui
      - api
