version: "3.7"
services:
  ui:
    build: ./ui
    volumes:
      - ./ui/:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  api:
    build: ./api
    volumes:
      - ./api/:/app
    ports:
      - "4000:4000"
